version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - viral_usher_data:/data
    environment:
      - WORKDIR=/data
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL:-}
      - S3_REGION=${S3_REGION:-us-east-1}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-}
    restart: unless-stopped

volumes:
  viral_usher_data:
